const profileTypes = {
	SET_IS_LOADING: "SET_IS_LOADING",
	GET_USERS_POSTS_SUCCESS: "GET_USERS_POSTS_SUCCESS",
	GET_USERS_POSTS_FAIL: "GET_USERS_POSTS_FAIL",
	SET_LOADING_USERS_POSTS: "SET_LOADING_USERS_POSTS"
};

module.exports = profileTypes;
