const postTypes = {
	POST_SUCCESS: "POST_SUCCESS",
	POST_FAIL: "POST_FAIL",
	EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
	EDIT_POST_FAIL: "EDIT_POST_FAIL",
	DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
	DELETE_POST_FAIL: "DELETE_POST_FAIL",
	SET_IS_POSTING: "SET_IS_POSTING",
	SET_EDIT_MODE: "SET_EDIT_MODE",
	GET_POST_BY_ID_SUCCESS: "GET_POST_BY_ID_SUCCESS",
	GET_POST_BY_ID_FAIL: "GET_POST_BY_ID_FAIL"
};

export default postTypes;
