const authTypes = {
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAIL: "REGISTER_FAIL",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",
	AUTH_SUCCESS: "AUTH_SUCCESS",
	AUTH_FAIL: "AUTH_FAIL",
	SET_LOADING_USER: "SET_LOADING_USER",
	LOGOUT: "LOGOUT"
};

export default authTypes;
